### ISSUE TITLE
Unable to get the key file from Jio Router

### ISSUE THREAD

**Issue by arunabhabanerjee** [JFC-Group/JF-Customisation#29]
I ran the script but I got Failed output for all trying keys. Please help to get the key file from my Jio router.

Firmware: SRCMTF1_JCOW414_R2.41
Model No: JCOW414

Thank you in advance and I really appreciate your help.

**Comment by dmdhrumilmistry** [comment]
@itsyourap can you share procedure how do you extract keys from img file?
