### ISSUE TITLE
Autostart scripts not working

### ISSUE THREAD

**Issue by keshavgarg616** [JFC-Group/JF-Customisation#31]
Hi, I rooted my router today but I noticed that everytime it reboots,
telnet access is gone and I have to reupload the hacked config file...

my scripts both in /flash and /flash2 also do not run despite being both chmod +x and executable throught telnet

#!/bin/sh 
vsftpd /flash/vsftpd.conf &                                                                                                                                  
iptables -I fwInBypass -p tcp --dport 21 -m ifgroup --ifgroup-in 0x1/0x1 -j ACCEPT   

What can i DO?

**Comment by itsyourap** [comment]
Well you cannot do anything since `/pfrm2.0 isn't` writable.
