### ISSUE TITLE
Firmware URL changed

### ISSUE THREAD

**Issue by souravdas142** [JFC-Group/JF-Customisation#33]
Hi,

The firmware URL changed. currently with your method I am getting upto 2.49, but last night router upgraded to 2.52, and I didn't get the url for that firmware.

![image](https://github.com/JFC-Group/JF-Customisation/assets/24272753/26f6bdb7-26a7-434f-b069-2374da6b9077)

```bash
└──╼ $ wget --spider http://fota.slv.fxd.jiophone.net/ONT/Sercomm/JCOW414/SRCMTF1_JCOW414_R2.52.img
Spider mode enabled. Check if remote file exists.
--2023-09-05 08:34:42--  http://fota.slv.fxd.jiophone.net/ONT/Sercomm/JCOW414/SRCMTF1_JCOW414_R2.52.img
Resolving fota.slv.fxd.jiophone.net (fota.slv.fxd.jiophone.net)... 2405:200:1606:1731::312c:b0b9, 2405:200:1606:1731::312c:b0ba, 49.44.194.80, ...
Connecting to fota.slv.fxd.jiophone.net (fota.slv.fxd.jiophone.net)|2405:200:1606:1731::312c:b0b9|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
Remote file does not exist -- broken link!!!
```

**Comment by itsyourap** [comment]
Yes I know..
We also have not been able to track the latest upgrade URL since it happened without notice..

We are trying...

**Comment by d5aqoep** [comment]
Is it possible to downgrade the firmware? People are saying they are unable to downgrade.

**Comment by Derpitron** [comment]
Anyone know any method?

**Comment by itsyourap** [comment]
The only way we know how to downgrade is to already have root access to the router.

Closing this issue now. If any breakthrough arrives, we will reopen this

**Comment by Naitik1208** [comment]
https://fota.slv.kai.jiophone.net/XPGNO/DIN460/S404W_102/yTPaHbfA4q.img i got a link for 3.10.2 can anyone fetch more links

> The only way we know how to downgrade is to already have root access to the router.
> 
> Closing this issue now. If any breakthrough arrives, we will reopen this
