### ISSUE TITLE
Cannot upload the .enc file in the Maintenance page

### ISSUE THREAD

**Issue by Vshindou** [JFC-Group/JF-Customisation#36]
I used the steps [here](https://github.com/JFC-Group/JF-Customisation/blob/master/Instructions/Alternate-Way-To-Get-Root-Access-JF-ONT-Home-Gateway.md) but it seems that they might have added a checksum verification

![Screenshot (2)](https://github.com/JFC-Group/JF-Customisation/assets/45714693/eed76b43-4377-4e03-92fc-4b5cac282e70)

So the above is the sha256 sum of the original .enc downloaded from the maintenance page

![Screenshot (3)](https://github.com/JFC-Group/JF-Customisation/assets/45714693/596c2b50-c154-434e-8b45-939d91d5ca48)

Here is the checksum of the new file created with the modifications on the instructions page as you can see they are different 
I have verified that the original file works following which i tried to use the modified file and i get this error 

![Screenshot (4)](https://github.com/JFC-Group/JF-Customisation/assets/45714693/066a5869-ca7d-4edb-9d2a-307a8c338781)

Here are my device details

Firmware Version  SRCMTF1_JCO4032_R2.52.1
 
Hardware Version   0003

 
Model Name   JCO4032

Please do help me out

**Comment by itsyourap** [comment]
If you correctly follow the steps and ensure that there is no line break in the first line before appending `os.execute(...)`, you need not to update the checksum.

Checksum is checked only after executing the command, which should produce a malformed webpage containing the output of `passwd` command as the initial lines and then the resultant html code...

As per your screenshot, the webpage returned isn't malformed, meaning you must have mistaken a step.

Can you please recheck it?

Also if you do have Telegram, send me your decrypted config to me at t.me/itsyourap

**Comment by raj9-11** [comment]
got the same issue, already checked about the line break in first line there ain't any. kindly help!

**Comment by Addster09** [comment]
@raj9-11 have you fixed it and if yes then how?

**Comment by raj9-11** [comment]
> @raj9-11 have you fixed it and if yes then how?

no if anyone has found then please update!

**Comment by raj9-11** [comment]
> @raj9-11 have you fixed it and if yes then how?

guys, when you use the keyguesser u get 2 line as output
1st line: xxxx**serialnumber**xxxx
2nd line: YYYYYYYYYYYYYYY
the key is YYYYYYYYYYYY (2nd line) and not the one with serial number in it.
and donot use the -iter 10000 it doesn't work, jst ignore the warning.

**Comment by itsyourap** [comment]
Not sure if your issue is solved or not but we are not able to identify the issue here.
So closing this issue until any new leads.
