### ISSUE TITLE
Jiotv_go package for mips

### ISSUE THREAD

**Issue by ksmanu1997** [JFC-Group/JF-Customisation#53]
This will initialise successfully but web UI isn't accessible.
![Screenshot_20240719-011714](https://github.com/user-attachments/assets/563f8307-6cfc-4af8-b228-9bb20be9a2b2)
![Screenshot_20240719-011746](https://github.com/user-attachments/assets/5f0ebe88-1617-412f-a113-84e4eb16a3c2)

**Comment by itsyourap** [comment]
Please run the following command before running the JioTV_Go binary:
```
/pfrm2.0/bin/iptables -I fwInBypass -p tcp --dport 5001 -m ifgroup --ifgroup-in 0x1/0x1 -j ACCEPT
```

This commands adds iptables rule to allow TCP connections to the port 5001.

**Comment by ksmanu1997** [comment]
Thanks
