### ISSUE TITLE
OpenVpn possible?

### ISSUE THREAD

**Issue by vaibhavramdasi** [JFC-Group/JF-Customisation#56]
I have followed the steps to get entware setup. I am now trying to get openvpn-openssl configured on router. It seems like TUN kernel module is not available and without that vpn server does not start. Has anyone tried setting-up OpenVPN successfully?

**Comment by vaibhav423** [comment]
@vaibhavramdasi did u try this https://files.lancethepants.com/Binaries/openvpn/mipsel/openvpn%202.5-git_12-4-2019/openvpn , as most of the binaries from this work for me on JCO4032 for example ssh client works well for me , please let me know if that vpn works for you
