### ISSUE TITLE
Issue in Root Access

### ISSUE THREAD

**Issue by adithyapi4** [JFC-Group/JF-Customisation#57]
I followed all the steps mentioned in [https://github.com/JFC-Group/JF-Customisation/blob/main/Instructions/Alternate-Way-To-Get-Root-Access-JF-ONT-Home-Gateway.md](url). But when I try to restore the modified file I get a page with the following text.
[Root_Access.txt](https://github.com/user-attachments/files/17002820/Root_Access.txt)

**Comment by itsyourap** [comment]
```shell
Changing password for root
New password: 
Bad password: too weak
Retype password: 
Password for root changed by root
Changing password for root
New password: 
Bad password: too weak
Retype password: 
Password for root changed by root
```

This basically means your root password was successfully changed and you definitely have root access now.
