### ISSUE TITLE
KeyGuesser

### ISSUE THREAD

**Issue by GOAT0P** [JFC-Group/JF-Customisation#58]
What to do if Keyguesser can't provide the correct key?

**Comment by itsyourap** [comment]
Depends on the version of your router firmware. If it is somewhat around or more than R2.52, then keyguesser is the only option for now. Generally, it should work.

If it doesn't, check if you can get your router firmware img using the following [tutorial](https://github.com/JFC-Group/JF-Customisation/tree/main/Router%20Firmware). If you cannot, then just comment down your router firmware version here.

**Comment by GOAT0P** [comment]
SRCMTF1_JCOW414_R2.52.1

There you go man. Appreciate the help.

**Comment by itsyourap** [comment]
It's a JCOW414 with R2.52.1
`keyguesser.py` should work with this

**Comment by GOAT0P** [comment]
Nah man, it's not working.

**Comment by itsyourap** [comment]
You have Telegram? If yes, then message me at [itsyourap](https://t.me/itsyourap) with your encrypted config file and your default Router SSID.

**Comment by itsyourap** [comment]
Closing since issue is resolved via Telegram
