### ISSUE TITLE
Still working? 

### ISSUE THREAD

**Issue by Shinchan7222** [JFC-Group/JF-Customisation#59]
I want to open ftp ( to access usb files) and port forwarding ( for my camera)

**Comment by Shinchan7222** [comment]
(main) $ openssl aes-128-cbc -d -kfile "RAROTBJ00039044_JCOW411.enc" -in "RAROTBJ00039044_JCOW411.enc" -out "RAROTBJ00039044_JCOW411.txt"
*** WARNING : deprecated key derivation used.
Using -iter or -pbkdf2 would be better.
bad decrypt
8082F6F227790000:error:1C800064:Provider routines:ossl_cipher_unpadblock:bad decrypt:providers/implementations/ciphers/ciphercommon_block.c:124:
@Shinchan7222

**Comment by Shinchan7222** [comment]
Trying Key : zuFbKywMhJjVEhk35GRAROTBJ00039044
Success : AD816E42C391E7199E92705583073189
@Shinchan7222 ➜ /workspaces/IG-Maker (main) $ aes-128-cbc -d -pass file:key.txt -in RAROTBJ00039044_JCOW411.enc -out output.txt
bash: aes-128-cbc: command not found
@Shinchan7222 ➜ /workspaces/IG-Maker (main) $ openssl aes-128-cbc -d -pass file:key.txt -in RAROTBJ00039044_JCOW411.enc -out output.txt
*** WARNING : deprecated key derivation used.
Using -iter or -pbkdf2 would be better.
@Shinchan7222 ➜ /workspaces/IG-Maker (main) $

**Comment by itsyourap** [comment]
> @Shinchan7222 ➜ /workspaces/IG-Maker (main) $ openssl aes-128-cbc -d -pass file:key.txt -in RAROTBJ00039044_JCOW411.enc -out output.txt
> *** WARNING : deprecated key derivation used. Using -iter or -pbkdf2 would be better.

This means that the decryption is successful. Please check the folder. It will contain the decrypted config `RAROTBJ00039044_JCOW411.txt`.

**Comment by Shinchan7222** [comment]
It's not Decrypted it's in unreadable formate

**Comment by Shinchan7222** [comment]
[RAROTBJ00039044_JCOW411.zip](https://github.com/user-attachments/files/17306502/RAROTBJ00039044_JCOW411.zip)
inFileName = "RAROTBJ00039044_JCOW411.enc" # Full name of the encrypted config backup file                    #
outFileName = "RAROTBJ00039044_JCOW411.txt" # Name of output file if the decryption is successful             #
routerSerial = "RAROTBJ00039044" # Your Router's Serial Number                                                #
routerSsid = "5G"  # Default Router SSID without the 'JioFiber-' prefix 

![image](https://github.com/user-attachments/assets/c6c8dfe0-ee71-481e-8141-aa1ca36c5509)

**Comment by Shinchan7222** [comment]
can you please decrypt it for me if your free

**Comment by Shinchan7222** [comment]
![image](https://github.com/user-attachments/assets/89135556-1b51-4f95-a514-9d6bc56e577b)

**Comment by itsyourap** [comment]
> Your Router's Serial Number # routerSsid = "5G" # Default Router SSID without the 'JioFiber-' prefix

Here you have to use the default SSID which is written on the back of your Router box.
Something like "JioFiber-Nxyao"

So `routerSsid = "Nxyao"`

**Comment by Shinchan7222** [comment]
THANK YOU I WAS ABLE TO DECRYPT IT BUT NEW ISSUE CAME UP

![image](https://github.com/user-attachments/assets/6e96dfaf-110f-49b7-8243-e5bef23a9bf0)

**Comment by Shinchan7222** [comment]
![image](https://github.com/user-attachments/assets/90f58d48-dce2-42d8-94e0-dde2f20c2909)
worked thank you so much bro, is there anyway to open a port? thanks

**Comment by itsyourap** [comment]
> Is there anyway to open a port?

`iptables -I fwInBypass -p tcp --dport <PORT-NUMBER> -m ifgroup --ifgroup-in 0x1/0x1 -j ACCEPT`

**Comment by Shinchan7222** [comment]
sorry i meant port forward

**Comment by itsyourap** [comment]
> sorry i meant port forward

Port Forwarding IPv4 isnt possible afaik. 
For IPv6, refer to [this article](https://www.reddit.com/r/HomeNetworking/comments/14g4udp/how_to_host_servers_on_jio_fiber_home_network/)

**Comment by Shinchan7222** [comment]
![image](https://github.com/user-attachments/assets/5b0b273e-423d-4160-968f-bc1d4fc0cb6c)
ahhhhhhhh

**Comment by Shinchan7222** [comment]
and can you tell me how do i run an sh file
on boot
