### ISSUE TITLE
New Update SRCMTF1_JCOW414_R2.57 removes the Backup & Restore Option

### ISSUE THREAD

**Issue by ksmanu1997** [JFC-Group/JF-Customisation#61]
New Update SRCMTF1_JCOW414_R2.57 removes the Backup & Restore Option, How could I access them to restore modified enc file? Any new trick?

**Comment by itsyourap** [comment]
Not yet. Will update if we find anything.

**Comment by ksmanu1997** [comment]
ok thanks!
