### ISSUE TITLE
Disable TR-069

### ISSUE THREAD

**Issue by IfranAli8K** [JFC-Group/JF-Customisation#63]
How to disable the TR-069? Is there any way to disable it? The old methods seems to show a checksum error while uploading the file with modified TR-069 stats.

**Comment by itsyourap** [comment]
The old method still works as expected. You have to re-encrypt the config with the valid checksum.

You can also get root and change the config file directly at `/flash/teamf1.cfg.ascii`, `/flash/teamf1.cfg.ascii.bkp` and `/tmp/system.db` and restart your router.

**Comment by IfranAli8K** [comment]
How do I re-encrypt the config with the valid checksum?

**Comment by itsyourap** [comment]
> How do I re-encrypt the config with the valid checksum?

https://github.com/JFC-Group/JF-Customisation/blob/main/Instructions/Encrypt-Router-Configuration-File.md
