### ISSUE TITLE
Cannot find the option to backup/restore the config file 

### ISSUE THREAD

**Issue by shamxl** [JFC-Group/JF-Customisation#66]
firmware version: `SKYWTF1_JCOW407_R2.57`

**Comment by viraniac** [comment]
Check the instructions here - https://broadband.forum/threads/jiofiber-router-jco4032-settings-import-export.231300/

**Comment by itsyourap** [comment]
Closing as resolved via https://github.com/JFC-Group/JF-Customisation/issues/66#issuecomment-2457535359
